### ISSUE TITLE
option() 메소드 수정하기

### ISSUE THREAD

**Issue by heski0709** [heski0709/mini-project#1]
**문제 제기**
- 하나의 메뉴만 옵션을 선택할 수 있다.

**기능 요약**
- 메뉴 별로 옵션 기능 추가

**기능 설명**
- 여러 메뉴가 선택이 되더라도 메뉴마다 옵션을 추가 할 수 있도록 한다.

**할일 목록**
- 

**비고**
-

**Comment by jissuk** [comment]
수정 완료
